export const modulesS1 = [
    {
      module: "Algorithmique Avancée & Complexité",
      coef: 3,
      hasTD: true,
      hasTP: true,
      td: "",
      tp: "",
      exam: "",
      moy: "0.00",
    },
    {
      module: "Bases de Données Avancées",
      coef: 3,
      hasTD: true,
      hasTP: true,
      td: "",
      tp: "",
      exam: "",
      moy: "0.00",
    },
    {
      module: "Ingénierie des Exigences",
      coef: 3,
      hasTD: true,
      hasTP: false,
      td: "",
      tp: "",
      exam: "",
      moy: "0.00",
    },
    {
      module: "Méthodes de Conception de Logiciels & Design Patterns",
      coef: 3,
      hasTD: true,
      hasTP: true,
      td: "",
      tp: "",
      exam: "",
      moy: "0.00",
    },
    {
      module: "Compilation Avancée",
      coef: 2,
      hasTD: false,
      hasTP: true,
      td: "",
      tp: "",
      exam: "",
      moy: "0.00",
    },
    {
      module: "Paradigmes de Programmation",
      coef: 2,
      hasTD: false,
      hasTP: true,
      td: "",
      tp: "",
      exam: "",
      moy: "0.00",
    },
    {
      module: "Réseaux Avancés",
      coef: 1,
      hasTD: false,
      hasTP: true,
      td: "",
      tp: "",
      exam: "",
      moy: "0.00",
    },
    {
      module: "Module au choix",
      coef: 1,
      hasTD: false,
      hasTP: false,
      td: "",
      tp: "",
      exam: "",
      moy: "0.00",
    },
  ];