export const modulesS3 = [
  {
    module: "Reconnaissance des Formes et Vision Artificielle",
    coef: 3,
    hasTD: true,
    hasTP: true,
    td: "",
    tp: "",
    exam: "",
    moy: "0.00",
  },
  {
    module: "Traitement du Langage Naturel",
    coef: 2,
    hasTD: true,
    hasTP: false,
    td: "",
    tp: "",
    exam: "",
    moy: "0.00",
  },
  {
    module: "IA Générative",
    coef: 2,
    hasTD: true,
    hasTP: false,
    td: "",
    tp: "",
    exam: "",
    moy: "0.00",
  },
  {
    module: "Business Intelligence",
    coef: 2,
    hasTD: true,
    hasTP: false,
    td: "",
    tp: "",
    exam: "",
    moy: "0.00",
  },
  {
    module: "Systèmes Multi-Agents",
    coef: 3,
    hasTD: true,
    hasTP: true,
    td: "",
    tp: "",
    exam: "",
    moy: "0.00",
  },
  {
    module: "Systèmes Embarqués et IoT",
    coef: 2,
    hasTD: true,
    hasTP: true,
    td: "",
    tp: "",
    exam: "",
    moy: "0.00",
  },
  {
    module: "Startup & Professional Development",
    coef: 2,
    hasTD: false,
    hasTP: false,
    td: "",
    tp: "",
    exam: "",
    moy: "0.00",
  },
  {
    module: "Séminaires et Workshops",
    coef: 1,
    hasTD: false,
    hasTP: false,
    td: "",
    tp: "",
    exam: "",
    moy: "0.00",
  },
];
