export const modulesS1 = [
  {
    module: "Apprentissage Automatique",
    coef: 3,
    hasTD: false,
    hasTP: true,
    td: "",
    tp: "",
    exam: "",
    moy: "0.00",
  },
  {
    module: "Bases de Données Avancées",
    coef: 3,
    hasTD: true,
    hasTP: true,
    td: "",
    tp: "",
    exam: "",
    moy: "0.00",
  },
  {
    module: "Réseaux Avancés",
    coef: 3,
    hasTD: true,
    hasTP: true,
    td: "",
    tp: "",
    exam: "",
    moy: "0.00",
  },
  {
    module: "Python Avancé pour la Science des Données",
    coef: 2,
    hasTD: false,
    hasTP: true,
    td: "",
    tp: "",
    exam: "",
    moy: "0.00",
  },
  {
    module: "Traitement et Analyse d’Images",
    coef: 3,
    hasTD: false,
    hasTP: true,
    td: "",
    tp: "",
    exam: "",
    moy: "0.00",
  },
  {
    module: "Cloud Computing et Big Data",
    coef: 2,
    hasTD: false,
    hasTP: true,
    td: "",
    tp: "",
    exam: "",
    moy: "0.00",
  },
  {
    module: "Séminaires et Workshops",
    coef: 1,
    hasTD: false,
    hasTP: false,
    td: "",
    tp: "",
    exam: "",
    moy: "0.00",
  },
];
