export const modulesS2 = [
    {
      module: "Architectures Logicielles",
      coef: 3,
      hasTD: true,
      hasTP: true,
      td: "",
      tp: "",
      exam: "",
      moy: "0.00",
    },
    {
      module: "Architectures Orientées Services",
      coef: 3,
      hasTD: true,
      hasTP: true,
      td: "",
      tp: "",
      exam: "",
      moy: "0.00",
    },
    {
      module: "Systèmes d'Information Coopératifs",
      coef: 3,
      hasTD: true,
      hasTP: false,
      td: "",
      tp: "",
      exam: "",
      moy: "0.00",
    },
    {
      module: "Sémantiques Formelles des Langages de Programmation",
      coef: 3,
      hasTD: true,
      hasTP: false,
      td: "",
      tp: "",
      exam: "",
      moy: "0.00",
    },
    {
      module: "Systèmes Multi Agents",
      coef: 2,
      hasTD: false,
      hasTP: true,
      td: "",
      tp: "",
      exam: "",
      moy: "0.00",
    },
    {
      module: "Machine Learning",
      coef: 2,
      hasTD: true,
      hasTP: true,
      td: "",
      tp: "",
      exam: "",
      moy: "0.00",
    },
    {
      module: "Gestion de Projets Informatiques",
      coef: 1,
      hasTD: false,
      hasTP: true,
      td: "",
      tp: "",
      exam: "",
      moy: "0.00",
    },
    {
      module: "Module au choix",
      coef: 1,
      hasTD: false,
      hasTP: false,
      td: "",
      tp: "",
      exam: "",
      moy: "0.00",
    },
  ];