export const modulesS2 = [
    {
      module: "Méthodes de Conception Avancées",
      coef: 2,
      hasTD: true,
      hasTP: true,
      td: "",
      tp: "",
      exam: "",
      moy: "0.00",
    },
    {
      module: "Apprentissage Profond",
      coef: 3,
      hasTD: false,
      hasTP: true,
      td: "",
      tp: "",
      exam: "",
      moy: "0.00",
    },
    {
      module: "Calcul Haute Performance",
      coef: 2,
      hasTD: true,
      hasTP: true,
      td: "",
      tp: "",
      exam: "",
      moy: "0.00",
    },
    {
      module: "Algorithmique Avancée et Complexité",
      coef: 2,
      hasTD: true,
      hasTP: true,
      td: "",
      tp: "",
      exam: "",
      moy: "0.00",
    },
    {
      module: "Optimisation et Métaheuristiques",
      coef: 3,
      hasTD: false,
      hasTP: true,
      td: "",
      tp: "",
      exam: "",
      moy: "0.00",
    },
    {
      module: "Processus Stochastiques",
      coef: 2,
      hasTD: true,
      hasTP: false,
      td: "",
      tp: "",
      exam: "",
      moy: "0.00",
    },
    {
      module: "Web Avancé et Micro-Services",
      coef: 2,
      hasTD: false,
      hasTP: true,
      td: "",
      tp: "",
      exam: "",
      moy: "0.00",
    },
    {
      module: "Séminaires et Workshops",
      coef: 1,
      hasTD: false,
      hasTP: false,
      td: "",
      tp: "",
      exam: "",
      moy: "0.00",
    },
  ];